spring:
  application:
    name: winterchen
  datasource:
      right:
          url: jdbc:mysql://127.0.0.1:3306/right?characterEncoding=utf8&useSSL=false
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 200
          initialSize: 50
          maxWait: 10000
          minIdle: 20
          logAbandoned: false
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          removeAbandoned: true
          removeAbandonedTimeout: 1800
      teacher:
        url: jdbc:mysql://127.0.0.1:3306/teacher?characterEncoding=utf8&useSSL=false
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 50
        maxWait: 10000
        minIdle: 20
        logAbandoned: false
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: true
        removeAbandonedTimeout: 1800
      world:
        url: jdbc:mysql://127.0.0.1:3306/world?characterEncoding=utf8&useSSL=false
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 50
        maxWait: 10000
        minIdle: 20
        logAbandoned: false
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: true
        removeAbandonedTimeout: 1800
      school:
        url: jdbc:mysql://127.0.0.1:3306/teacher?characterEncoding=utf8&useSSL=false
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 50
        maxWait: 10000
        minIdle: 20
        logAbandoned: false
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: true
        removeAbandonedTimeout: 1800
server:
  port: 8089
  session-timeout : 1000000 #用户回话session过期时间，以秒为单位
  tomcat:
    #context-path: /xycar
    #access-log-enabled: true
    #basedir: ${logging.path}
    uri-encoding: UTF-8

mybatis:
    type-aliases-package: com.winterchen.model
    mapper-locations: classpath:mapper/**.xml
endpoints.shutdown:
  enabled: true
  sensitive: false

management:
  health:
    solr:
      enabled: false
    db:
      enabled: false
    elasticsearch:
      enabled: false
    jms:
      enabled: false
    mail:
      enabled: false
    mongo:
      enabled: false
    rabbit:
      enabled: false
    redis:
      enabled: false
  add-application-context-header: false
eureka:
  client:
    healthcheck:
      enable: true
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: http://127.0.0.1:7999/eureka/,http://127.0.0.1:7998/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    leaseRenewalIntervalInSeconds: 30